project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - fridge.qmd
    - PublishingWebsiteNotes.qmd


website:
  title: "Alea Wilbur-Mujtaba"
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - fridge.qmd
      - PublishingWebsiteNotes.qmd
    right: 
      - icon: envelope
        href: awilbu@uic.edu
      - icon: github
        href: https://github.com/AleaWM
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
